apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleepybox-deployment
  labels:
    app: sleepybox
spec:
  replicas: 2 # {"$ref":"#/definitions/io.k8s.cli.setters.replicas"}
  selector:
    matchLabels:
      app: sleepybox
  template:
    metadata:
      labels:
        app: sleepybox
    spec:
      containers:
      - name: alpine
        image: alpine:3.12.0 # {"$ref":"#/definitions/io.k8s.cli.setters.alpine-image"}
        command: ["sleep"]
        args: ["36000"]
